name: Generate ASCII

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Install Cowsay Program
              run: sudo apt-get install cowsay -y
            - name: Execute Cowsay
              run: cowsay -f dragon "Run for cover, I'm a dragon ... RAWR" >> dragon.txt
            - name: Uploading file to artifact
              uses: actions/upload-artifact@v7
              with:
                  name: dragon-text-file
                  path: dragon.txt
    test:
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            - name: Downloading file
              uses: actions/download-artifact@v7
              with:
                  name: dragon-text-file

            - name: Test file
              run: grep -i "dragon" dragon.txt

    deploy:
        needs: [test]
        runs-on: ubuntu-latest
        steps:
            - name: Downloading file
              uses: actions/download-artifact@v7
              with:
                  name: dragon-text-file

            - name: Reading file
              run: cat dragon.txt
