name: My First GitHub Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checking out to my github repository
              uses: actions/checkout@v6
            - name: Welcome Message
              run: echo "Initiating My GitHub Action"

            - name: List Files
              run: ls -a

            - name: Read Files
              run: cat README.md
